on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to run a subset of the regression tests
    steps:
    - name: Run regression test
      id: run
      uses: bioimagesuiteweb/bisweb/actions/push@devel
    - name: Results
      run: echo "${{ steps.run.outputs.result}}"
    - name: Logfile
      run: echo "${{ steps.run.outputs.logfile}}"
    
