on: 
  schedule:
    - cron: '15 9 * * *'

jobs:
  regression_job:
    runs-on: ubuntu-latest
    name: Regression Test
    steps:
    - name: Regression
      id: regression
      uses: bioimagesuiteweb/bisweb/actions/test@devel
