on: [push]

jobs:
  test_job:
    runs-on: ubuntu-18.04
    name: Docker test for bisweb
    steps:
    - name: Run
      id: run      
      uses: bioimagesuiteweb/bisweb/actions/test@devel
      env:
        BIS_FIRST_TEST: 1
        BIS_LAST_TEST: 1000
    - name: Results
      run: echo "${{ steps.run.outputs.result}}"
    - name: Logfile
      run: echo "${{ steps.run.outputs.logfile}}"
    