on: [push]

jobs:
  test_job:
    runs-on: ubuntu-18.04
    name: Docker test for bisweb
    steps:
    - name: Run
      id: run      
      uses: bioimagesuiteweb/bisweb/actions/docker@devel
      env:
        BIS_FIRST_TEST: 12
        BIS_LAST_TEST: 20
    - name: Results
      run: echo "${{ steps.run.outputs.result}}"
    - name: Upload results
      uses: actions/upload-artifact@v1
      with:
        name: Logs
        path: /basedir/bisweb/src/build/logs
