on: [push]

jobs:
  test_job:
    runs-on: ubuntu-18.04
    name: Docker test for bisweb
    steps:
    - name: Run
      id: run      
      uses: bioimagesuiteweb/bisweb/actions/docker@devel
      env:
        BIS_FIRST_TEST: 2
        BIS_LAST_TEST: 20
    - name: Results
      run: echo "${{ steps.run.outputs.result}}"
    
    