on: [push]

jobs:
  hosted_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest]
    name: bisweb-test
    steps:
    - name: Global Prereqs
      run: |
        python3 -m pip install --upgrade pip setuptools 
        
    - name: Clone
      run: |
        mkdir c:\bisweb
        mkdir c:\bisweb\src
        cd c:\bisweb\bisweb
        git clone https://github.com/bioimagesuiteweb/bisweb src
        cd src
        git checkout devel
        git pull
        copy npm-shrinkwrap-orig.json npm-shrinkwrap.json
    - name: Clone Plugin
      run: |
        cd c:\bisweb
        mkdir c:\bisweb\gpl
        git clone https://github.com/bioimagesuiteweb/gplcppcode gpl
        cd gpl
        git pull
    - name : Python Prereqs
      run: |
        cd c:\bisweb\src
        python3 -m pip install --user -r biswebpython/config/requirements.txt
    - name : JS Prereqs
      run: |
        cd c:\bisweb\src
        npm install -d
        node config\createbuild.js
    - name : Build
      run: |
        cd c:\bisweb\src\build
        echo "-------------------------------------------------"
        echo "Beginning build"
        echo "-------------------------------------------------"
        bash c:\bisweb\src\compiletools\fullbuild.bat
        cd c:\bisweb\src
    - name : Test
      run : bash c:\bisweb\src\actions\hosted\dockeractiontest.bat 
      id: run    
    - name: Results
      run: echo "${{ steps.run.outputs.result}}"
    - name: Store Results
      uses: actions/upload-artifact@v1
      with:
        name: logs
        path: c:\bisweb\src\build\output\logs
#    - name: Store Electron
#      uses: actions/upload-artifact@v1
#      with:
#        name: electron
#        path: c:\bisweb\src\build\output\electron
#    - name: Store Binaries
#      uses: actions/upload-artifact@v1
#      with:
#        name: binaries
#        path: c:\bisweb\src\build\output\binaries
    - name: Store Libraries
      uses: actions/upload-artifact@v1
      with:
        name: libraries
        path: c:\bisweb\src\build\output\libraries
